// Component tests run the real UI handlers against a small DOM fixture.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(){
 const nodes=[],ids={},writes=[];let serial=0;
 class Element{
  constructor(tag,attrs='',text='',dynamic=false){this.tag=tag;this.attrs={};this.dataset={};this.dynamic=dynamic;this.style={};this.value='';this.checked=false;this.hidden=false;this.textContent=text.replace(/<[^>]+>/g,'');this.classList={toggle:()=>{}};for(const m of attrs.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){this.attrs[m[1]]=m[2]??'';if(m[1].startsWith('data-'))this.dataset[m[1].slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=m[2];}this.id=this.attrs.id;this.value=this.attrs.value||'';if(this.id)ids[this.id]=this;nodes.push(this);}
  set innerHTML(value){this.html=value;if(this.id==='content'){for(let i=nodes.length-1;i>=0;i--)if(nodes[i].dynamic){if(nodes[i].id)delete ids[nodes[i].id];nodes.splice(i,1);}parse(value,true);}}
  get innerHTML(){return this.html||'';}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,fn){this['on'+k]=fn;}showModal(){this.open=true;}close(){this.open=false;}focus(){}reset(){}click(){this.onclick?.();}querySelectorAll(s){return select(s);}closest(){return this;}remove(){}
 }
 function parse(html,dynamic=false){for(const match of html.matchAll(/<(button|input|select|textarea|dialog|form|div|span|p|h1|h2|label|nav|section|aside|main|a)\b([^>]*)(?:>([^<]*))?/g))new Element(match[1],match[2],match[3]||'',dynamic);}
 function select(s){if(s==='nav button')return nodes.filter(n=>n.tag==='button'&&n.dataset.view);if(s==='dialog[open]')return nodes.filter(n=>n.tag==='dialog'&&n.open);if(s.includes(','))return s.split(',').flatMap(select);if(s.startsWith('#'))return ids[s.slice(1)]?[ids[s.slice(1)]]:[];const attr=s.match(/^\[([^\]]+)\]$/);if(attr)return nodes.filter(n=>n.attrs[attr[1]]!==undefined);if(s.startsWith('.'))return nodes.filter(n=>(n.attrs.class||'').split(' ').includes(s.slice(1)));return nodes.filter(n=>n.tag===s);}
 parse(fs.readFileSync('docs/index.html','utf8'));
 const document={documentElement:{dataset:{}},querySelector:s=>select(s)[0]||null,querySelectorAll:select,createElement:()=>new Element('a')};
 const context={document,console,structuredClone,Date,crypto:{randomUUID:()=>`generated-${++serial}`},setTimeout:()=>1,clearTimeout:()=>{},localStorage:{getItem:()=>null,setItem:()=>{}},matchMedia:()=>({matches:false}),Blob,URL,CompassoAccount:{init:()=>{},save:s=>writes.push(structuredClone(s)),isPrivate:()=>true}};context.window=context;vm.createContext(context);
 for(const f of ['finance.js','planner.js','app.js','redesign.js'])vm.runInContext(fs.readFileSync('docs/'+f,'utf8'),context,{filename:f});
 vm.runInContext("window.compassoReplaceState({version:1,opening:0,tasks:[],entries:[],bills:[],library:[]})",context);
 const run=code=>vm.runInContext(code,context),set=(id,v)=>ids[id].value=v,submit=id=>ids[id].onsubmit({preventDefault(){}});
 return {context,ids,writes,run,set,submit,select};
}
test('agenda edita horário, reduz duração e retorna tarefa ao backlog',()=>{const h=harness();h.run("window.compassoReplaceState({version:1,opening:0,tasks:[{id:'t',name:'Estudo',area:'Estudos',date:'2026-10-01',time:'19:00',duration:60,done:false}],entries:[],bills:[],library:[]});openPlan('t','2026-10-01');");h.ids.planReduce.click();assert.equal(h.ids.planDuration.value,30);h.set('planDate','2026-10-02');h.set('planTime','20:00');h.submit('planForm');assert.equal(h.writes.at(-1).tasks[0].date,'2026-10-02');assert.equal(h.writes.at(-1).tasks[0].time,'20:00');h.run("openPlan('t','2026-10-02')");h.ids.planUnschedule.click();assert.equal(h.writes.at(-1).tasks[0].date,'');});
test('treino recorrente altera só a ocorrência e aparece na agenda',()=>{const h=harness();h.run("window.compassoReplaceState({version:1,opening:0,tasks:[],entries:[],bills:[],library:[],health:[{id:'gym',name:'Musculação',kind:'training',days:[1,5],from:'2026-10-01',time:'12:00',duration:60,exceptions:{}}]});openHealth('gym','2026-10-02');");h.set('healthName','Treino curto');h.set('healthKind','training');h.set('healthDate','2026-10-02');h.set('healthTime','12:00');h.set('healthDuration','30');h.set('healthScope','one');h.submit('healthForm');const t=h.writes.at(-1).health[0];assert.equal(t.name,'Musculação');assert.equal(t.exceptions['2026-10-02'].name,'Treino curto');assert.equal(t.exceptions['2026-10-02'].duration,30);assert.ok(h.ids.content.innerHTML.includes('Treino curto'));});
test('lançamento parcelado usa centavos e pagamento registra a data escolhida',()=>{const h=harness();h.run('openEntry()');for(const [id,v] of Object.entries({amount:'100,00',method:'credit',kind:'expense',description:'Compra',category:'Outros',date:'2026-10-01',firstMonth:'2026-11',card:'PicPay',count:'3'}))h.set(id,v);h.submit('entryForm');assert.equal(h.writes.at(-1).entries[0].allocations.reduce((s,a)=>s+a.amount,0),10000);h.run("payingBill=state.bills[0].id");h.set('billDate','2026-11-10');h.submit('billForm');assert.equal(h.writes.at(-1).bills[0].paidDate,'2026-11-10');assert.equal(h.writes.at(-1).bills[0].paid,true);});
test('tema alterna no celular sem alterar os dados da conta',()=>{const h=harness();h.ids.mobileTheme.click();assert.equal(h.run('theme'),'dark');assert.equal(h.writes.length,0);});
